import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/layout/Navigation";
import RecoilProvider from "@/components/recoil/recoilComponent";
import AuthProvider from "@/components/auth/AuthProvider";
import QueryProvider from "@/components/query/QueryProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ReelTalk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilProvider>
          <QueryProvider>
            <AuthProvider>
              <Navigation />
              {children}
              {/* 버셀 성능 테스트용 */}
              <Analytics />
              <SpeedInsights />
            </AuthProvider>
          </QueryProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}
